theme = "lynx"
title = "JAlcocerT Data Analytics Portfolio"
#baseURL = "http://192.168.1.11:1313/"
baseURL = "https://jalcocert.github.io/Portfolio"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "JAlcocerT Portfolio"
  headline = """
  From AI to Data Analytics
  """
  
  image = "fossengineer.png" 
  links = [
        { fossengineer = { href = "https://jalcocertech.com/", text = "Work with Me" } },
        { GHPages = { href = "https://jalcocert.github.io/JAlcocerT", text = "My Learning Process" } },    
        { github = "https://github.com/JAlcocerT/"},

        { youtube = "https://www.youtube.com/@JAlcocerTech" },

    { linkedin = "https://www.linkedin.com/in/jalcocert/" },
    { medium = "https://medium.com/@jalcocert" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true