backend:
  name: local
  # For production, change to 'github', 'gitlab', or 'bitbucket' and add repo/auth config
  # e.g. name: github
  # repo: user/repo
  # branch: main
  # site_domain: your-site.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
